export const initialUsers = [
  {
    id: 'user_rakesh_1',
    name: 'Rakesh',
    email: 'rakesh.explorer@tripplanner.ai',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Explorer',
    tripsCount: 12,
    countriesVisited: 8,
    moneySaved: 1250,
    co2Saved: 120,
    plan: 'free',
  },
];

export const initialTrips = [
  {
    id: 'trip_bali_1',
    title: 'Bali Getaway',
    destination: 'Bali, Indonesia',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
    status: 'Confirmed',
    startDate: 'May 25, 2025',
    endDate: 'May 31, 2025',
    days: 6,
    travelers: '2 Travelers',
    travelersCount: 2,
    tripType: 'Relaxation & Adventure',
    estimatedCost: 1149,
    actualCost: 1080,
    activitiesCount: 12,
    progress: 75,
    budgetBreakdown: { flights: 450, hotels: 350, activities: 200, food: 100, transport: 49 },
  },
  {
    id: 'trip_swiss_2',
    title: 'Swiss Alps Expedition',
    destination: 'Switzerland',
    country: 'Switzerland',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&auto=format&fit=crop&q=80',
    status: 'Planning',
    startDate: 'Jul 10, 2025',
    endDate: 'Jul 16, 2025',
    days: 6,
    travelers: '2 Travelers',
    travelersCount: 2,
    tripType: 'Mountains & Hiking',
    estimatedCost: 1299,
    actualCost: 1299,
    activitiesCount: 10,
    progress: 40,
    budgetBreakdown: { flights: 550, hotels: 420, activities: 180, food: 100, transport: 49 },
  },
  {
    id: 'trip_kyoto_3',
    title: 'Kyoto Cherry Blossom Tour',
    destination: 'Kyoto, Japan',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80',
    status: 'Completed',
    startDate: 'Mar 28, 2025',
    endDate: 'Apr 02, 2025',
    days: 5,
    travelers: '1 Traveler',
    travelersCount: 1,
    tripType: 'Cultural & Heritage',
    estimatedCost: 1049,
    actualCost: 980,
    activitiesCount: 14,
    progress: 100,
    budgetBreakdown: { flights: 480, hotels: 320, activities: 120, food: 90, transport: 39 },
  },
];

export const initialDestinations = [
  {
    id: 'dest_bali',
    name: 'Bali, Indonesia',
    country: 'Indonesia',
    rating: 4.8,
    reviewCount: '1.2k',
    duration: '7 Days Trip',
    price: 899,
    category: 'Beach',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
    description: 'Island of the Gods featuring lush volcanic mountains, iconic rice terraces, exotic beaches, and deeply spiritual temple ceremonies.',
    bestTime: 'Apr to Oct',
    weather: 'Sunny & Tropical',
    temp: '29°C',
    popularAttractions: ['Tegalalang Rice Terrace', 'Uluwatu Temple', 'Nusa Penida', 'Mount Batur', 'Seminyak Beach'],
    recommendedHotels: [
      { name: 'Viceroy Bali Ubud', pricePerNight: 280, rating: 4.9, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&auto=format&fit=crop&q=80' },
      { name: 'Ayana Resort & Spa', pricePerNight: 210, rating: 4.8, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&auto=format&fit=crop&q=80' },
    ],
    topRestaurants: [
      { name: 'Locavore Ubud', specialty: 'Modern Indonesian Fine Dining', priceRange: '$$$$' },
      { name: 'Warung Babi Guling Ibu Oka', specialty: 'Authentic Roast Pork', priceRange: '$' },
    ],
    tags: ['Tropical', 'Surfing', 'Culture', 'Temples', 'Nightlife'],
  },
  {
    id: 'dest_swiss',
    name: 'Switzerland',
    country: 'Switzerland',
    rating: 4.9,
    reviewCount: '942',
    duration: '6 Days Trip',
    price: 1299,
    category: 'Mountains',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&auto=format&fit=crop&q=80',
    description: 'Majestic snow-capped Alps, pristine glacial lakes, storybook chalets, and world-class panoramic railway journeys across Europe.',
    bestTime: 'Jun to Sep & Dec to Mar',
    weather: 'Crisp Alpine',
    temp: '18°C / 2°C in Winter',
    popularAttractions: ['Jungfraujoch Top of Europe', 'Matterhorn in Zermatt', 'Lake Geneva', 'Lucerne Chapel Bridge'],
    recommendedHotels: [
      { name: 'The Chedi Andermatt', pricePerNight: 450, rating: 4.9, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&auto=format&fit=crop&q=80' },
      { name: 'Hotel Schweizerhof Bern', pricePerNight: 320, rating: 4.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&auto=format&fit=crop&q=80' },
    ],
    topRestaurants: [
      { name: 'Restaurant de l’Hôtel de Ville', specialty: 'Michelin Swiss Cuisine', priceRange: '$$$$' },
      { name: 'Fondue Chalet Swiss', specialty: 'Traditional Cheese Fondue', priceRange: '$$' },
    ],
    tags: ['Skiing', 'Hiking', 'Lakes', 'Scenic Trains', 'Luxury'],
  },
  {
    id: 'dest_kyoto',
    name: 'Kyoto, Japan',
    country: 'Japan',
    rating: 4.7,
    reviewCount: '1.1k',
    duration: '5 Days Trip',
    price: 1049,
    category: 'Culture',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80',
    description: 'The cultural heart of Japan boasting thousands of classical Buddhist temples, gardens, imperial palaces, and traditional wooden geisha machiya.',
    bestTime: 'Mar to May & Oct to Nov',
    weather: 'Mild & Pleasant',
    temp: '21°C',
    popularAttractions: ['Fushimi Inari Taisha', 'Kinkaku-ji (Golden Pavilion)', 'Arashiyama Bamboo Grove', 'Gion Historic District'],
    recommendedHotels: [
      { name: 'Hoshinoya Kyoto Ryokan', pricePerNight: 380, rating: 4.9, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&auto=format&fit=crop&q=80' },
      { name: 'The Thousand Kyoto', pricePerNight: 230, rating: 4.7, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&auto=format&fit=crop&q=80' },
    ],
    topRestaurants: [
      { name: 'Gion Karyo', specialty: 'Authentic Kaiseki Dining', priceRange: '$$$$' },
      { name: 'Ippudo Ramen Kyoto', specialty: 'Tonkotsu Ramen', priceRange: '$' },
    ],
    tags: ['Heritage', 'Temples', 'Cherry Blossoms', 'Culinary', 'Tea Ceremony'],
  },
  {
    id: 'dest_iceland',
    name: 'Iceland',
    country: 'Iceland',
    rating: 4.9,
    reviewCount: '753',
    duration: '6 Days Trip',
    price: 1399,
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&auto=format&fit=crop&q=80',
    description: 'Land of fire and ice where gigantic glaciers meet erupting geysers, black sand coastlines, and the ethereal glow of the Aurora Borealis.',
    bestTime: 'Sep to Mar (Aurora) or Jun to Aug (Midnight Sun)',
    weather: 'Cool & Dynamic',
    temp: '12°C in Summer / -1°C in Winter',
    popularAttractions: ['Blue Lagoon Geothermal Spa', 'Golden Circle Route', 'Skógafoss Waterfall', 'Diamond Beach & Jökulsárlón'],
    recommendedHotels: [
      { name: 'The Retreat at Blue Lagoon', pricePerNight: 550, rating: 4.9, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&auto=format&fit=crop&q=80' },
      { name: 'ION Adventure Hotel', pricePerNight: 290, rating: 4.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&auto=format&fit=crop&q=80' },
    ],
    topRestaurants: [
      { name: 'Dill Restaurant Reykjavik', specialty: 'New Nordic Cuisine', priceRange: '$$$$' },
      { name: 'Bæjarins Beztu Pylsur', specialty: 'Famous Icelandic Hot Dogs', priceRange: '$' },
    ],
    tags: ['Northern Lights', 'Volcanoes', 'Glaciers', 'Waterfalls', 'Geothermal'],
  },
];

export const initialBookings = [
  {
    id: 'book_fl_1',
    type: 'flight',
    provider: 'Singapore Airlines',
    title: 'Flight SQ 942: SIN → DPS (Bali)',
    bookingCode: 'SQ-884920',
    date: 'May 25, 2025 • 08:20 AM',
    status: 'Confirmed',
    price: 450,
    details: {
      Departure: '08:20 AM (SIN Terminal 3)',
      Arrival: '11:05 AM (DPS Denpasar)',
      Seat: '14A & 14B',
      Baggage: '30kg Checked',
    },
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'book_ht_1',
    type: 'hotel',
    provider: 'Viceroy Bali Resort & Spa',
    title: 'Deluxe Valley Pool Villa (6 Nights)',
    bookingCode: 'VB-449102',
    date: 'May 25 – May 31, 2025',
    status: 'Confirmed',
    price: 350,
    details: {
      'Check-in': 'May 25, 2:00 PM',
      'Check-out': 'May 31, 11:00 AM',
      Guests: '2 Adults',
      Perks: 'Free Floating Breakfast & Airport Transfer',
    },
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'book_act_1',
    type: 'activity',
    provider: 'Bali Ocean Adventures',
    title: 'Nusa Penida Private Speedboat & Snorkeling Tour',
    bookingCode: 'BOA-77319',
    date: 'May 27, 2025 • 07:00 AM',
    status: 'Confirmed',
    price: 110,
    details: {
      Includes: 'Speedboat tickets, Manta Point Snorkel, English Guide, Lunch',
      Pickup: 'Hotel Lobby 06:15 AM',
    },
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=300&auto=format&fit=crop&q=80',
  },
];

export const initialExpenses = [
  { id: 'exp_1', tripId: 'trip_bali_1', category: 'Flights', amount: 450, title: 'Roundtrip Flights (2 pax)', date: 'May 10, 2025', isPlanned: true },
  { id: 'exp_2', tripId: 'trip_bali_1', category: 'Hotels', amount: 350, title: 'Viceroy Resort deposit & stay', date: 'May 12, 2025', isPlanned: true },
  { id: 'exp_3', tripId: 'trip_bali_1', category: 'Activities', amount: 110, title: 'Nusa Penida boat & tour', date: 'May 15, 2025', isPlanned: true },
  { id: 'exp_4', tripId: 'trip_bali_1', category: 'Activities', amount: 45, title: 'Ubud Swing & Rice Terraces entry', date: 'May 26, 2025', isPlanned: false },
  { id: 'exp_5', tripId: 'trip_bali_1', category: 'Food', amount: 65, title: 'Jimbaran Sunset Seafood dinner', date: 'May 25, 2025', isPlanned: false },
  { id: 'exp_6', tripId: 'trip_bali_1', category: 'Food', amount: 35, title: 'Locavore tasting menu lunch', date: 'May 26, 2025', isPlanned: false },
  { id: 'exp_7', tripId: 'trip_bali_1', category: 'Transport', amount: 49, title: 'Private island chauffeur & Grab rides', date: 'May 28, 2025', isPlanned: true },
];

export const initialSavedPlaces = [
  {
    id: 'sav_1',
    destinationId: 'dest_bali',
    destinationName: 'Bali, Indonesia',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&auto=format&fit=crop&q=80',
    rating: 4.8,
    price: 899,
    category: 'Beach & Culture',
    addedAt: '2 days ago',
    notes: 'Must visit Tegalalang and Nusa Penida',
  },
  {
    id: 'sav_2',
    destinationId: 'dest_swiss',
    destinationName: 'Switzerland',
    country: 'Switzerland',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=400&auto=format&fit=crop&q=80',
    rating: 4.9,
    price: 1299,
    category: 'Alps & Scenic Trains',
    addedAt: '1 week ago',
    notes: 'Glacier express train planned for summer',
  },
];

export const initialNotifications = [
  {
    id: 'notif_1',
    title: 'Flight Price Drop Alert!',
    description: 'Bali round-trip flights dropped 18% for your selected May dates.',
    time: '10m ago',
    read: false,
    type: 'deal',
  },
  {
    id: 'notif_2',
    title: 'Itinerary Optimized with AI',
    description: 'Added 2 hidden-gem sunset cafes in Jimbaran to your Day 1 schedule.',
    time: '1 hour ago',
    read: false,
    type: 'ai',
  },
  {
    id: 'notif_3',
    title: 'Hotel Booking Confirmed',
    description: 'Viceroy Bali Resort reservation voucher is now ready to download.',
    time: 'Yesterday',
    read: false,
    type: 'booking',
  },
];
