import React, { useState } from 'react';
import {
  Calendar,
  Clock,
  MapPin,
  Sparkles,
  Plus,
  Compass,
  DollarSign,
  CheckCircle2,
  Share2,
  Download,
  Navigation,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { BackButton } from '../components/BackButton';

export const ItinerariesPage = () => {
  const { activeTrip } = useApp();
  const [selectedDayIndex, setSelectedDayIndex] = useState(0);
  const [notification, setNotification] = useState(null);
  const [isNavigating, setIsNavigating] = useState(false);

  const days = activeTrip.daysItinerary?.length
    ? activeTrip.daysItinerary
    : [
        {
          dayNumber: 1,
          title: 'Day 1',
          subtitle: 'Arrival & Beach Relaxation',
          thumbnail:
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
          activities: [
            {
              timeSlot: 'Morning',
              time: '10:00 AM',
              title: 'Arrive at Ngurah Rai International Airport',
              description: 'Private driver meet & greet with fresh tropical leis and cool mineral water.',
              location: 'Denpasar / Seminyak',
              duration: '1.5 hrs',
              cost: 25,
              category: 'transport',
            },
            {
              timeSlot: 'Afternoon',
              time: '02:00 PM',
              title: 'Seminyak Beachfront Stroll & Chilled Coconut',
              description: 'Dip toes in warm surf and relax on double daybeds along the coastline.',
              location: 'Seminyak Beach',
              duration: '3 hrs',
              cost: 10,
              category: 'relaxation',
            },
            {
              timeSlot: 'Evening',
              time: '06:30 PM',
              title: 'Jimbaran Bay Sunset Grilled Seafood Dinner',
              description: 'Fresh red snapper, jumbo tiger prawns, and calamari with toes in the sand.',
              location: 'Jimbaran Beach',
              duration: '2.5 hrs',
              cost: 45,
              category: 'food',
            },
          ],
        },
        {
          dayNumber: 2,
          title: 'Day 2',
          subtitle: 'Ubud Culture & Sacred Temples',
          thumbnail:
            'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=80',
          activities: [
            {
              timeSlot: 'Morning',
              time: '08:30 AM',
              title: 'Tegalalang Rice Terraces & Jungle Swing',
              description: 'Hike through UNESCO subak irrigation terraces and fly across lush jungle canopies.',
              location: 'Tegalalang, Ubud',
              duration: '3 hrs',
              cost: 30,
              category: 'sightseeing',
            },
            {
              timeSlot: 'Afternoon',
              time: '01:00 PM',
              title: 'Sacred Monkey Forest Sanctuary',
              description: 'Walk amongst 700+ playful Balinese long-tailed macaques and ancient banyan trees.',
              location: 'Padangtegal, Ubud',
              duration: '2 hrs',
              cost: 15,
              category: 'culture',
            },
            {
              timeSlot: 'Evening',
              time: '07:00 PM',
              title: 'Ubud Royal Palace Cultural Kecak Dance',
              description: 'Dramatic fire dance performance accompanied by 50 rhythmic chanting vocalists.',
              location: 'Ubud Palace',
              duration: '2 hrs',
              cost: 20,
              category: 'culture',
            },
          ],
        },
      ];

  const currentDay = days[selectedDayIndex] || days[0];

  const getCategoryColor = (category) => {
    switch (category) {
      case 'food':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200';
      case 'culture':
      case 'sightseeing':
        return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'adventure':
        return 'bg-indigo-50 text-indigo-700 border-indigo-200';
      case 'relaxation':
        return 'bg-pink-50 text-pink-700 border-pink-200';
      default:
        return 'bg-slate-50 text-slate-700 border-slate-200';
    }
  };

  const handleExportPDF = () => {
    const itineraryContent = `=====================================================
${activeTrip.title.toUpperCase()} - OFFICIAL TRIP ITINERARY
Destination: ${activeTrip.destination}
Dates: ${activeTrip.startDate} to ${activeTrip.endDate}
Travelers: ${activeTrip.travelers}
Generated by TripPlanner AI (Gemini Engine)
=====================================================

${days.map((d) => `
[${d.title} - ${d.subtitle}]
${d.activities.map((a) => `• ${a.time} (${a.timeSlot}): ${a.title}
  Location: ${a.location} | Duration: ${a.duration} | Est. Cost: $${a.cost}
  Note: ${a.description}`).join('\n\n')}
-----------------------------------------------------`).join('\n')}

Offline Sync Key: TP-SYNC-${Math.floor(100000 + Math.random() * 900000)}
All passes synced with offline cache.
=====================================================`;

    const blob = new Blob([itineraryContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Itinerary_${activeTrip.destination.replace(/\s+/g, '_')}_Offline.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setNotification('Full itinerary exported for offline access!');
    setTimeout(() => setNotification(null), 3500);
  };

  const handleShareTrip = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(window.location.href);
    }
    setNotification('Trip share link copied to clipboard!');
    setTimeout(() => setNotification(null), 3000);
  };

  return (
    <div id="itineraries-detailed-planner-page" className="space-y-6">
      {/* Top Breadcrumb / Back Button Bar */}
      <div className="flex items-center justify-between">
        <BackButton label="Back to Trips" fallbackPage="Trips" />
        <span className="text-xs font-semibold text-slate-400">Daily Itinerary</span>
      </div>

      {/* Toast Notification */}
      {notification && (
        <div className="p-3 bg-emerald-50 text-emerald-800 text-xs font-bold rounded-2xl border border-emerald-200 flex items-center gap-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{notification}</span>
        </div>
      )}

      {/* Header Banner */}
      <div className="bg-white rounded-3xl p-6 md:p-8 border border-slate-100/90 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 text-indigo-600 text-xs font-bold mb-1">
            <Sparkles className="w-4 h-4" />
            <span>AI Optimized Daily Itinerary</span>
          </div>
          <h2 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">
            {activeTrip.title}
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 mt-1 flex items-center gap-2">
            <MapPin className="w-4 h-4 text-slate-400" />
            <span>
              {activeTrip.destination} • {activeTrip.startDate} - {activeTrip.endDate} • {activeTrip.travelers}
            </span>
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleExportPDF}
            className="px-4 py-2.5 rounded-xl text-xs font-bold text-slate-700 bg-slate-50 hover:bg-slate-100 border border-slate-200 flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Itinerary</span>
          </button>
          <button
            onClick={handleShareTrip}
            className="px-4 py-2.5 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-sky-600 to-blue-600 hover:from-sky-500 hover:to-blue-500 shadow-md shadow-blue-500/20 flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>Share Trip</span>
          </button>
        </div>
      </div>

      {/* Days Tabs selector */}
      <div className="flex items-center gap-2.5 overflow-x-auto pb-1 scrollbar-none">
        {days.map((day, idx) => (
          <button
            key={day.dayNumber}
            onClick={() => setSelectedDayIndex(idx)}
            className={`px-5 py-3 rounded-2xl text-xs font-extrabold transition-all whitespace-nowrap cursor-pointer flex flex-col items-start min-w-[120px] ${
              selectedDayIndex === idx
                ? 'bg-gradient-to-r from-sky-600 via-blue-600 to-indigo-600 text-white shadow-lg shadow-blue-500/20 scale-102'
                : 'bg-white text-slate-700 hover:bg-slate-50 border border-slate-200/80'
            }`}
          >
            <span className="text-[10px] uppercase opacity-80">{day.title}</span>
            <span className="truncate max-w-[130px]">{day.subtitle}</span>
          </button>
        ))}
      </div>

      {/* Selected Day Timeline & Details */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Timeline Activities Column */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-white rounded-3xl p-6 border border-slate-200/70 shadow-xs">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-6">
              <div>
                <span className="text-xs font-bold text-sky-600 uppercase tracking-wider">
                  {currentDay.title} Schedule
                </span>
                <h3 className="text-xl font-extrabold text-slate-900 mt-0.5">
                  {currentDay.subtitle}
                </h3>
              </div>

              <span className="text-xs font-bold text-slate-500 bg-slate-50 px-3 py-1 rounded-full border border-slate-100">
                {currentDay.activities?.length || 3} Experiences
              </span>
            </div>

            {/* Activities List */}
            <div className="space-y-6 relative before:absolute before:left-4 before:top-3 before:bottom-3 before:w-0.5 before:bg-slate-100">
              {currentDay.activities?.map((act, aIdx) => (
                <div key={aIdx} className="relative flex items-start gap-5 pl-2 group">
                  {/* Timeline Dot */}
                  <div className="w-5 h-5 rounded-full bg-white border-4 border-sky-600 shadow-md shrink-0 relative z-10 mt-1" />

                  {/* Activity Card */}
                  <div className="flex-1 bg-slate-50/70 hover:bg-slate-50 p-4 rounded-2xl border border-slate-100 transition-all space-y-2">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                      <div className="flex items-center gap-2">
                        <span className="font-extrabold text-xs text-sky-600">{act.time}</span>
                        <span
                          className={`text-[10px] font-bold px-2 py-0.5 rounded-md border uppercase ${getCategoryColor(
                            act.category
                          )}`}
                        >
                          {act.category || 'Sightseeing'}
                        </span>
                      </div>
                      <span className="text-xs font-extrabold text-slate-800">
                        {act.cost > 0 ? `$${act.cost}` : 'Free Entry'}
                      </span>
                    </div>

                    <h4 className="font-extrabold text-sm sm:text-base text-slate-900">
                      {act.title}
                    </h4>
                    <p className="text-xs text-slate-600 leading-relaxed font-normal">
                      {act.description}
                    </p>

                    <div className="flex items-center justify-between pt-2 border-t border-slate-200/60 text-xs text-slate-400">
                      <div className="flex items-center gap-1.5">
                        <MapPin className="w-3.5 h-3.5 text-slate-400" />
                        <span>{act.location}</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5" />
                        <span>{act.duration}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Day Summary & Map Mini Widget */}
        <div className="space-y-5">
          {/* Day Photo Card */}
          <div className="bg-white rounded-3xl overflow-hidden border border-slate-200/70 shadow-xs">
            <div className="relative h-48 w-full bg-slate-900">
              <img
                src={currentDay.thumbnail || 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80'}
                alt={currentDay.title}
                referrerPolicy="no-referrer"
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent" />
              <div className="absolute bottom-3 left-4 right-4 text-white">
                <span className="text-[10px] font-bold bg-sky-600 px-2 py-0.5 rounded-full">
                  Day Highlight
                </span>
                <h4 className="font-extrabold text-base mt-1">{currentDay.subtitle}</h4>
              </div>
            </div>

            <div className="p-4 space-y-3">
              <div className="flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Estimated Day Cost</span>
                <span className="font-bold text-slate-900">
                  $
                  {currentDay.activities?.reduce(
                    (sum, a) => sum + (a.cost || 0),
                    0
                  ) || 80}
                </span>
              </div>
              <div className="flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Transit Comfort</span>
                <span className="font-bold text-emerald-600">High (Private Vehicle)</span>
              </div>

              {isNavigating ? (
                <div className="mt-3 p-3 bg-emerald-50 rounded-2xl border border-emerald-200 space-y-2 animate-in fade-in">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-extrabold text-emerald-800 flex items-center gap-1.5">
                      <Navigation className="w-3.5 h-3.5 text-emerald-600 animate-pulse" />
                      GPS Active: Route Guidance
                    </span>
                    <button
                      onClick={() => setIsNavigating(false)}
                      className="text-[10px] font-bold text-red-600 hover:underline cursor-pointer"
                    >
                      Exit
                    </button>
                  </div>
                  <p className="text-[11px] text-emerald-700 font-medium">
                    Next Stop: {currentDay.activities?.[0]?.title || 'Next scheduled stop'} (12 mins, 4.2 km)
                  </p>
                </div>
              ) : (
                <button
                  onClick={() => {
                    setIsNavigating(true);
                    setNotification(`Live turn-by-turn navigation started for ${currentDay.title}`);
                    setTimeout(() => setNotification(null), 3000);
                  }}
                  className="w-full mt-2 py-2.5 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-sky-600 via-blue-600 to-indigo-600 hover:from-sky-500 hover:to-indigo-500 shadow-md shadow-blue-500/20 flex items-center justify-center gap-1.5 transition-all cursor-pointer"
                >
                  <Navigation className="w-3.5 h-3.5" />
                  <span>Start Live Navigation</span>
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
